---
version: "2.0"
services:
  app:
    image: ljxha471758/llama-factory
    expose:
      - port: 7860
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - llamafactory-cli webui --host 0.0.0.0 --port 7860
    params:
      storage:
        data:
          mount: /root/.cache
          readOnly: false
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 16
        memory:
          size: 128Gi
        gpu:
          units: 4
          attributes:
            vendor:
              nvidia:
        storage:
          size: 500Gi
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1