---
version: "2.0"

services:
  chia:
    image: cryptoandcoffee/akash-chia:111
    expose:
      - port: 8080
        as: 80
        proto: tcp
        to:
          - global: true
    expose:
      - port: 5572
        as: 5572
        proto: tcp
        to:
          - global: true
    env:
#############################REQUIRED##############################
###################################################################
      - VERSION=1.3.5 #Always check https://github.com/Chia-Network/chia-blockchain/releases
      - CONTRACT=
      - FARMERKEY=
      - PLOTTER=madmax
        #Choose your plotter software - madmax, bladebit, bladebit-disk
      - FINAL_LOCATION=local
        #Set to "local" to access finished plots through web interface.
        #Set to "upload" and finished plots will be uploaded to a SSH destination like user@ip:/home/user/plots
      - CPU_UNITS=8
      - MEMORY_UNITS=8Gi
      - STORAGE_UNITS=915Gi
        #Must match CPU/Memory/Storage units defined in resources.
#############################OPTIONAL##############################
###################################################################
      #- RAMCACHE=32G
        #Used only for PLOTTER=bladebit-disk, you must increase the memory resources requested below with this additional cache size.
###################################################################
      - RCLONE=true
      - TOTAL_PLOTS=1000
###################################################################
# Uncomment the variables below when set FINAL_LOCATION=upload to enable remote uploading
#      - REMOTE_HOST=changeme.com #SSH upload host
#      - REMOTE_LOCATION=changeme #SSH upload location like /root/plots
#      - REMOTE_PORT=22 #SSH upload port
#      - REMOTE_USER=changeme #SSH upload user
#      - REMOTE_PASS=changme #SSH upload password
#      - UPLOAD_BACKGROUND=true
#        Change to true to enable multiple background uploading of plots, this is the best option to use use 100% of your bandwidth.

profiles:
  compute:
    chia:
      resources:
#If you change these values you must update the CPU_UNITS / MEMORY_UNITS / STORAGE_UNITS in the env to match.
        cpu:
          units: 8.0 #min 6 max 256
        memory:
          size: 6Gi #min 6Gi max 512Gi
        storage:
          size: 915Gi #min 384Gi max 32000Gi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      attributes:
        chia-plotting: "true"
      pricing:
        chia:
          denom: uakt
          amount: 100000
deployment:
  chia:
    akash:
      profile: chia
      count: 1
