version: '2.0'
services:
  bamboo-crypto:
    image: ghcr.io/bamboo-crypto/bamboo:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    command:
      - bash
      - c
      - /bin/server
profiles:
  compute:
    bamboo-crypto:
      resources:
        cpu:
          units: 4
        memory:
          size: 4Gi
        storage:
          - size: 64Gi
    db:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 8Gi
  placement:
    akash:
      #######################################################
      #Keep this section to deploy on trusted providers
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      #######################################################
      #Remove this section to deploy on untrusted providers
      #Miners: You can receive more bids from more providers by removing this section
      #Beware* You may have deployment, security, or other issues on untrusted providers
      #https://docs.akash.network/providers/akash-audited-attributes
      pricing:
        bamboo-crypto:
          denom: uakt
          amount: 10000
deployment:
  bamboo-crypto:
    akash:
      profile: bamboo-crypto
      count: 1
